export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}
import { Box, Accordion, Heading, Flex, Icon, For, Span, Stack, Text, Link as ChakraLink } from "@chakra-ui/react"
import NextLink from "next/link"
import {
    MdHome,
    MdOutlineNoFood,
    MdShoppingCart,
    MdCategory,
    MdFastfood,
    MdSettings,
    MdDashboard,
    MdLogout
} from "react-icons/md";

//apenas login recebe as edições feitas aqui
export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div suppressHydrationWarning  >
            <Box display="flex" h="100vh" w="100%"  >
                <Stack
                    w="200px"
                    color="white"
                    p={2}
                    position="relative"
                    boxShadow="sm"
                    justify="space-between"
                >
                    <Box>
                        <Flex height={"130px"} bg={"blue.600"} align={"flex-end"} justify={"flex-start"} w="100%" borderRadius={"md"} position={"relative"}>
                            <Flex m="2">
                                <Icon size="lg" color="white">
                                    <MdOutlineNoFood />
                                </Icon>
                                <Heading fontWeight="normal" pl="2">EasyFood</Heading>
                            </Flex>
                        </Flex>
                        <Stack pt={6} gap="8" color={"fg.muted"} >
                            <For each={["subtle"]} >
                                {(variant) => (
                                    <Stack gap="2" key={variant} >
                                        <Accordion.Root variant={variant} collapsible size={"sm"} spaceY={1} >
                                            {items.map((item, index) => (
                                                <Accordion.Item key={index} value={item.value} >
                                                    <Accordion.ItemTrigger _open={{ bg: "bg.subtle" , color:"fg.muted"}} >
                                                        <Icon fontSize="lg" color="fg.subtle">
                                                            {item.icon}
                                                        </Icon>
                                                        <Span flex="1">{item.title}</Span>
                                                        <Accordion.ItemIndicator />
                                                    </Accordion.ItemTrigger>
                                                    <Accordion.ItemContent >
                                                        <Accordion.ItemBody >
                                                            <Text textStyle="sm">
                                                                <ChakraLink
                                                                    {...cleanLink}
                                                                    asChild>
                                                                    <NextLink href={item.link}>
                                                                        {item.text}
                                                                    </NextLink>
                                                                </ChakraLink>
                                                            </Text>
                                                        </Accordion.ItemBody>
                                                    </Accordion.ItemContent>
                                                </Accordion.Item>
                                            ))}
                                        </Accordion.Root>
                                    </Stack>
                                )}
                            </For>
                        </Stack>
                    </Box>
                        <Text textStyle="sm" p={2}>
                            <ChakraLink
                                {...cleanLink}
                                asChild>
                                <NextLink href='/login'>
                                    <Icon>
                                        <MdLogout />
                                    </Icon>
                                    Sair
                                </NextLink>
                            </ChakraLink>
                        </Text>
                </Stack>
                <Box flex="1"  >
                    {children}
                </Box>
            </Box>
        </div>
    )
}
const items = [
    {
        value: "a",
        title: "Home",
        text: "Pagina inicial",
        icon: <MdHome />,
        link: '/home'
    },
    {
        value: "b",
        title: "Pedidos",
        text: "Criar Pedido",
        icon: <MdShoppingCart />,
        link: '/pedidos'
    },
    {
        value: "c",
        title: "Categoria",
        text: "Criar Categoria",
        icon: <MdCategory />,
        link: '/categoria'
    },
    {
        value: "d",
        title: "Produtos",
        text: "Ver Produtos",
        icon: <MdFastfood />,
        link: '/produtos'
    },
    {
        value: "e",
        title: "Configurações",
        text: "Editar Config",
        icon: <MdSettings />,
        link: '/config'
    },
    {
        value: "f",
        title: "Dashabord",
        text: "Métricas",
        icon: <MdDashboard />,
        link: '/dashabord'
    },
];

const cleanLink = {
    border: "none",
    textDecoration: "none",
    _hover: { textDecoration: "none", color: "blue.600" },
    _active: { textDecoration: "none" },
    _focus: { boxShadow: "none", outline: "none" },
    _focusVisible: { boxShadow: "none", outline: "none" },
}
